on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: GitHub Packages And NPM Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@refactor-op'

      - name: Patch
        run: |
          node -e "const fs = require('fs'); const path = 'package.json'; const pkg = JSON.parse(fs.readFileSync(path)); pkg.name = '@refactor-op/' + pkg.name; fs.writeFileSync(path, JSON.stringify(pkg, null, 2));"
        
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}